import {
  basicForms,
  basicPricing,
  basicSubmissions,
  freeTrialForms,
  freeTrialPeriod,
  freeTrialPricing,
  freeTrialSubmissions,
  proForms,
  proPricing,
  proSubmissions,
} from "./envs";
import { IDesign, IIntegration, IPlanLanding } from "./interfaces";

export const minWidth640 = "(min-width: 640px)";
export const minute = 1000 * 60;
export const day = 24 * 60 * 60 * 1000;
export const paginationRange = 8;
export const paginationFrom = 0;
export const paginationTo = paginationRange;
export const planSettings = {
  freeTrial: {
    period: freeTrialPeriod,
    pricing: freeTrialPricing,
    forms: freeTrialForms,
    submissions: freeTrialSubmissions,
  },
  basic: {
    pricing: basicPricing,
    forms: basicForms,
    submissions: basicSubmissions,
  },
  pro: {
    pricing: proPricing,
    forms: proForms,
    submissions: proSubmissions,
  },
};
export const plans: IPlanLanding[] = [
  {
    name: "Starter",
    price: freeTrialPricing,
    features: [
      `${freeTrialForms} forms`,
      `${freeTrialSubmissions} submissions`,
      "Basic analytics (Submissions tracking)",
    ],
    highlighted: false,
    type: "free_trial",
    buttonLabel: "Start Free Trial",
  },
  {
    name: "Basic",
    price: basicPricing,
    features: [
      `${basicForms} forms`,
      `${basicSubmissions} submissions`,
      "Basic support (24h response time)",
      "Basic analytics (Submissions tracking)",
      "Basic templates",
      "Integrations (Soon)",
      "Email notifications (Soon)",
    ],
    highlighted: false,
    type: "basic",
    buttonLabel: "Upgrade to Basic",
  },
  {
    name: "Pro",
    price: proPricing,
    features: [
      "Everything from basic plan",
      `${proForms} forms`,
      `${proSubmissions} submissions`,
      "Priority support (6h response time)",
      "Remove Nebulaform branding",
      "Data export (CSV)",
      "Premium templates",
      "Premium analytics",
      "Premium integrations (Soon)",
      "Email notifications (Soon)",
      "More to come",
    ],
    highlighted: true,
    type: "pro",
    buttonLabel: "Upgrade to Pro",
  },
];
export const designTemplate: IDesign[] = [
  { label: "slate", tw_class: "" },
  { label: "gray", tw_class: "" },
  { label: "zinc", tw_class: "" },
  { label: "neutral", tw_class: "" },
  { label: "stone", tw_class: "" },
  { label: "red", tw_class: "" },
  { label: "orange", tw_class: "" },
  { label: "amber", tw_class: "" },
  { label: "yellow", tw_class: "" },
  { label: "lime", tw_class: "" },
  { label: "green", tw_class: "" },
  { label: "emerald", tw_class: "" },
  { label: "teal", tw_class: "" },
  { label: "cyan", tw_class: "" },
  { label: "sky", tw_class: "" },
  { label: "blue", tw_class: "" },
  { label: "indigo", tw_class: "" },
  { label: "violet", tw_class: "" },
  { label: "purple", tw_class: "" },
  { label: "fuchsia", tw_class: "" },
  { label: "pink", tw_class: "" },
  { label: "rose", tw_class: "" },
];
export const integrations: IIntegration[] = [
  {
    name: "Google Sheets",
    type: "google_sheets",
    enabled: true,
    description: "Connect with Google Sheets to automate data export directly to your spreadsheets.",
    pro: false,
    category: "database",
  },
  {
    name: "Zapier",
    type: "zapier",
    enabled: false,
    description: "Automate workflows by connecting different apps and services without writing code.",
    pro: true,
    category: "automation",
  },
  {
    name: "Slack",
    type: "slack",
    enabled: false,
    description: "Stay connected with real-time notifications and seamless communication through Slack.",
    pro: true,
    category: "communication",
  },
  {
    name: "Google Drive",
    type: "google_drive",
    enabled: false,
    description: "Automatically upload form submissions as files in Google Drive.",
    pro: true,
    category: "storage",
  },
  {
    name: "Notion",
    type: "notion",
    enabled: false,
    description: "Save form responses directly into your Notion databases for easy organization.",
    pro: true,
    category: "database",
  },
  {
    name: "Trello",
    type: "trello",
    enabled: false,
    description: "Convert form submissions into Trello cards automatically.",
    pro: true,
    category: "automation",
  },
  {
    name: "Airtable",
    type: "airtable",
    enabled: false,
    description: "Sync form responses with Airtable to organize and analyze your data.",
    pro: true,
    category: "database",
  },
  {
    name: "Webhooks",
    type: "webhooks",
    enabled: false,
    description: "Send form data to any endpoint via webhooks for custom automation.",
    pro: false,
    category: "automation",
  },
  {
    name: "Discord",
    type: "discord",
    enabled: false,
    description: "Get notified of form submissions directly in your Discord server.",
    pro: true,
    category: "communication",
  },
  {
    name: "Mailchimp",
    type: "mailchimp",
    enabled: false,
    description: "Add form respondents to your Mailchimp email lists automatically.",
    pro: true,
    category: "email_marketing",
  },
  {
    name: "HubSpot",
    type: "hubspot",
    enabled: false,
    description: "Send form leads directly to your HubSpot CRM for seamless customer management.",
    pro: true,
    category: "crm",
  },
  {
    name: "Salesforce",
    type: "salesforce",
    enabled: false,
    description: "Sync form responses with Salesforce to streamline lead and customer tracking.",
    pro: true,
    category: "crm",
  },
  {
    name: "SendGrid",
    type: "sendgrid",
    enabled: false,
    description: "Trigger automated emails via SendGrid when a form is submitted.",
    pro: true,
    category: "email_marketing",
  },
  {
    name: "Twilio",
    type: "twilio",
    enabled: false,
    description: "Send SMS notifications or confirmations using Twilio.",
    pro: true,
    category: "notifications",
  },
];
