import {
  basicForms,
  basicPricing,
  basicSubmissions,
  freeTrialForms,
  freeTrialPeriod,
  freeTrialPricing,
  freeTrialSubmissions,
  proForms,
  proPricing,
  proSubmissions,
} from "./envs";
import { IBlockViewSettings, IDesign, IIntegration } from "./interfaces";

export const minWidth640 = "(min-width: 640px)";
export const minute = 1000 * 60;
export const day = 24 * 60 * 60 * 1000;
export const paginationRange = 8;
export const paginationFrom = 0;
export const paginationTo = paginationRange;
export const planSettings = {
  freeTrial: {
    period: freeTrialPeriod,
    pricing: freeTrialPricing,
    forms: freeTrialForms,
    submissions: freeTrialSubmissions,
  },
  basic: {
    pricing: basicPricing,
    forms: basicForms,
    submissions: basicSubmissions,
  },
  pro: {
    pricing: proPricing,
    forms: proForms,
    submissions: proSubmissions,
  },
};
export const fallbackColor = "#1c1917";
export const designTemplate: IDesign[] = [
  { label: "slate", tw_class: "" },
  { label: "gray", tw_class: "" },
  { label: "zinc", tw_class: "" },
  { label: "neutral", tw_class: "" },
  { label: "stone", tw_class: "" },
  { label: "red", tw_class: "" },
  { label: "orange", tw_class: "" },
  { label: "amber", tw_class: "" },
  { label: "yellow", tw_class: "" },
  { label: "lime", tw_class: "" },
  { label: "green", tw_class: "" },
  { label: "emerald", tw_class: "" },
  { label: "teal", tw_class: "" },
  { label: "cyan", tw_class: "" },
  { label: "sky", tw_class: "" },
  { label: "blue", tw_class: "" },
  { label: "indigo", tw_class: "" },
  { label: "violet", tw_class: "" },
  { label: "purple", tw_class: "" },
  { label: "fuchsia", tw_class: "" },
  { label: "pink", tw_class: "" },
  { label: "rose", tw_class: "" },
];
export const integrations: IIntegration[] = [
  {
    name: "Google Sheets",
    type: "google_sheets",
    enabled: true,
    description: "Connect with Google Sheets to automate data export directly to your spreadsheets.",
    pro: false,
    category: "database",
  },
  {
    name: "Zapier",
    type: "zapier",
    enabled: false,
    description: "Automate workflows by connecting different apps and services without writing code.",
    pro: true,
    category: "automation",
  },
  {
    name: "Slack",
    type: "slack",
    enabled: false,
    description: "Stay connected with real-time notifications and seamless communication through Slack.",
    pro: true,
    category: "communication",
  },
  {
    name: "Google Drive",
    type: "google_drive",
    enabled: false,
    description: "Automatically upload form submissions as files in Google Drive.",
    pro: true,
    category: "storage",
  },
  {
    name: "Notion",
    type: "notion",
    enabled: false,
    description: "Save form responses directly into your Notion databases for easy organization.",
    pro: true,
    category: "database",
  },
  {
    name: "Trello",
    type: "trello",
    enabled: false,
    description: "Convert form submissions into Trello cards automatically.",
    pro: true,
    category: "automation",
  },
  {
    name: "Airtable",
    type: "airtable",
    enabled: false,
    description: "Sync form responses with Airtable to organize and analyze your data.",
    pro: true,
    category: "database",
  },
  {
    name: "Webhooks",
    type: "webhooks",
    enabled: false,
    description: "Send form data to any endpoint via webhooks for custom automation.",
    pro: false,
    category: "automation",
  },
  {
    name: "Discord",
    type: "discord",
    enabled: false,
    description: "Get notified of form submissions directly in your Discord server.",
    pro: true,
    category: "communication",
  },
  {
    name: "Mailchimp",
    type: "mailchimp",
    enabled: false,
    description: "Add form respondents to your Mailchimp email lists automatically.",
    pro: true,
    category: "email_marketing",
  },
  {
    name: "HubSpot",
    type: "hubspot",
    enabled: false,
    description: "Send form leads directly to your HubSpot CRM for seamless customer management.",
    pro: true,
    category: "crm",
  },
  {
    name: "Salesforce",
    type: "salesforce",
    enabled: false,
    description: "Sync form responses with Salesforce to streamline lead and customer tracking.",
    pro: true,
    category: "crm",
  },
  {
    name: "SendGrid",
    type: "sendgrid",
    enabled: false,
    description: "Trigger automated emails via SendGrid when a form is submitted.",
    pro: true,
    category: "email_marketing",
  },
  {
    name: "Twilio",
    type: "twilio",
    enabled: false,
    description: "Send SMS notifications or confirmations using Twilio.",
    pro: true,
    category: "notifications",
  },
];
export const blockViewSettings: IBlockViewSettings[] = [
  {
    block: "short_text",
    showName: true,
    showDescription: true,
    showPlaceholder: true,
    showIsIdentifier: false,
    showChar: true,
    showMaxChar: true,
    showMinChar: false,
    showMaxDate: false,
    showMinDate: false,
    showMaxScale: false,
    showMinScale: false,
    showOptions: false,
    showPosition: false,
    showRating: false,
    showRequired: true,
  },
  {
    block: "paragraph_text",
    showName: true,
    showDescription: true,
    showPlaceholder: true,
    showIsIdentifier: false,
    showChar: true,
    showMaxChar: true,
    showMinChar: false,
    showMaxDate: false,
    showMinDate: false,
    showMaxScale: false,
    showMinScale: false,
    showOptions: false,
    showPosition: false,
    showRating: false,
    showRequired: true,
  },
  {
    block: "multiple_choice",
    showName: true,
    showDescription: true,
    showPlaceholder: false,
    showIsIdentifier: false,
    showChar: false,
    showMaxChar: false,
    showMinChar: false,
    showMaxDate: false,
    showMinDate: false,
    showMaxScale: false,
    showMinScale: false,
    showOptions: true,
    showPosition: true,
    showRating: false,
    showRequired: true,
  },
  {
    block: "checkboxes",
    showName: true,
    showDescription: true,
    showPlaceholder: false,
    showIsIdentifier: false,
    showChar: false,
    showMaxChar: false,
    showMinChar: false,
    showMaxDate: false,
    showMinDate: false,
    showMaxScale: false,
    showMinScale: false,
    showOptions: true,
    showPosition: true,
    showRating: false,
    showRequired: true,
  },
  {
    block: "dropdown_menu",
    showName: true,
    showDescription: true,
    showPlaceholder: false,
    showIsIdentifier: false,
    showChar: false,
    showMaxChar: false,
    showMinChar: false,
    showMaxDate: false,
    showMinDate: false,
    showMaxScale: false,
    showMinScale: false,
    showOptions: true,
    showPosition: true,
    showRating: false,
    showRequired: true,
  },
  {
    block: "number_input",
    showName: true,
    showDescription: true,
    showPlaceholder: false,
    showIsIdentifier: false,
    showChar: false,
    showMaxChar: true,
    showMinChar: true,
    showMaxDate: false,
    showMinDate: false,
    showMaxScale: false,
    showMinScale: false,
    showOptions: false,
    showPosition: false,
    showRating: false,
    showRequired: true,
  },
  {
    block: "email_address",
    showName: true,
    showDescription: true,
    showPlaceholder: true,
    showIsIdentifier: true, // Only email can be identifier
    showChar: false,
    showMaxChar: false,
    showMinChar: false,
    showMaxDate: false,
    showMinDate: false,
    showMaxScale: false,
    showMinScale: false,
    showOptions: false,
    showPosition: false,
    showRating: false,
    showRequired: true,
  },
  {
    block: "star_rating",
    showName: true,
    showDescription: true,
    showPlaceholder: false,
    showIsIdentifier: false,
    showChar: false,
    showMaxChar: false,
    showMinChar: false,
    showMaxDate: false,
    showMinDate: false,
    showMaxScale: false,
    showMinScale: false,
    showOptions: false,
    showPosition: false,
    showRating: true,
    showRequired: true,
  },
  {
    block: "custom_scale",
    showName: true,
    showDescription: true,
    showPlaceholder: false,
    showIsIdentifier: false,
    showChar: false,
    showMaxChar: false,
    showMinChar: false,
    showMaxDate: false,
    showMinDate: false,
    showMaxScale: true,
    showMinScale: true,
    showOptions: false,
    showPosition: false,
    showRating: false,
    showRequired: true,
  },
  {
    block: "date_picker",
    showName: true,
    showDescription: true,
    showPlaceholder: false,
    showIsIdentifier: false,
    showChar: false,
    showMaxChar: false,
    showMinChar: false,
    showMaxDate: true,
    showMinDate: true,
    showMaxScale: false,
    showMinScale: false,
    showOptions: false,
    showPosition: false,
    showRating: false,
    showRequired: true,
  },
];
export const templateColors = [
  // Slate
  "#f8fafc",
  "#f1f5f9",
  "#e2e8f0",
  "#cbd5e1",
  "#94a3b8",
  "#64748b",
  "#475569",
  "#334155",
  "#1e293b",
  "#0f172a",
  // Gray
  "#f9fafb",
  "#f3f4f6",
  "#e5e7eb",
  "#d1d5db",
  "#9ca3af",
  "#6b7280",
  "#4b5563",
  "#374151",
  "#1f2937",
  "#111827",
  // Zinc
  "#fafafa",
  "#f4f4f5",
  "#e4e4e7",
  "#d4d4d8",
  "#a1a1aa",
  "#71717a",
  "#52525b",
  "#3f3f46",
  "#27272a",
  "#18181b",
  // Neutral
  "#ffffff",
  "#f5f5f5",
  "#e5e5e5",
  "#d4d4d4",
  "#a3a3a3",
  "#737373",
  "#525252",
  "#404040",
  "#262626",
  "#171717",
  // Stone
  "#fafaf9",
  "#f5f5f4",
  "#e7e5e4",
  "#d6d3d1",
  "#a8a29e",
  "#78716c",
  "#57534e",
  "#44403c",
  "#292524",
  "#1c1917",
  // Red
  "#fef2f2",
  "#fee2e2",
  "#fecaca",
  "#fca5a5",
  "#f87171",
  "#ef4444",
  "#dc2626",
  "#b91c1c",
  "#991b1b",
  "#7f1d1d",
  // Orange
  "#fff7ed",
  "#ffedd5",
  "#fed7aa",
  "#fdba74",
  "#fb923c",
  "#f97316",
  "#ea580c",
  "#c2410c",
  "#9a3412",
  "#7c2d12",
  // Amber
  "#fffbeb",
  "#fef3c7",
  "#fde68a",
  "#fcd34d",
  "#fbbf24",
  "#f59e0b",
  "#d97706",
  "#b45309",
  "#92400e",
  "#78350f",
  // Yellow
  "#fefce8",
  "#fef9c3",
  "#fef08a",
  "#fde047",
  "#facc15",
  "#eab308",
  "#ca8a04",
  "#a16207",
  "#854d0e",
  "#713f12",
  // Lime
  "#f7fee7",
  "#ecfccb",
  "#d9f99d",
  "#bef264",
  "#a3e635",
  "#84cc16",
  "#65a30d",
  "#4d7c0f",
  "#3f6212",
  "#365314",
  // Green
  "#f0fdf4",
  "#dcfce7",
  "#bbf7d0",
  "#86efac",
  "#4ade80",
  "#22c55e",
  "#16a34a",
  "#15803d",
  "#166534",
  "#14532d",
  // Emerald
  "#ecfdf5",
  "#d1fae5",
  "#a7f3d0",
  "#6ee7b7",
  "#34d399",
  "#10b981",
  "#059669",
  "#047857",
  "#065f46",
  "#064e3b",
  // Teal
  "#f0fdfa",
  "#ccfbf1",
  "#99f6e4",
  "#5eead4",
  "#2dd4bf",
  "#14b8a6",
  "#0d9488",
  "#0f766e",
  "#115e59",
  "#134e4a",
  // Cyan
  "#ecfeff",
  "#cffafe",
  "#a5f3fc",
  "#67e8f9",
  "#22d3ee",
  "#06b6d4",
  "#0891b2",
  "#0e7490",
  "#155e75",
  "#164e63",
  // Sky
  "#f0f9ff",
  "#e0f2fe",
  "#bae6fd",
  "#7dd3fc",
  "#38bdf8",
  "#0ea5e9",
  "#0284c7",
  "#0369a1",
  "#075985",
  "#0c4a6e",
  // Blue
  "#eff6ff",
  "#dbeafe",
  "#bfdbfe",
  "#93c5fd",
  "#60a5fa",
  "#3b82f6",
  "#2563eb",
  "#1d4ed8",
  "#1e40af",
  "#1e3a8a",
  // Indigo
  "#eef2ff",
  "#e0e7ff",
  "#c7d2fe",
  "#a5b4fc",
  "#818cf8",
  "#6366f1",
  "#4f46e5",
  "#4338ca",
  "#3730a3",
  "#312e81",
  // Violet
  "#f5f3ff",
  "#ede9fe",
  "#ddd6fe",
  "#c4b5fd",
  "#a78bfa",
  "#8b5cf6",
  "#7c3aed",
  "#6d28d9",
  "#5b21b6",
  "#4c1d95",
  // Purple
  "#faf5ff",
  "#f3e8ff",
  "#e9d5ff",
  "#d8b4fe",
  "#c084fc",
  "#a855f7",
  "#9333ea",
  "#7e22ce",
  "#6b21a8",
  "#581c87",
  // Fuchsia
  "#fdf4ff",
  "#fae8ff",
  "#f5d0fe",
  "#f0abfc",
  "#e879f9",
  "#d946ef",
  "#c026d3",
  "#a21caf",
  "#86198f",
  "#701a75",
  // Pink
  "#fdf2f8",
  "#fce7f3",
  "#fbcfe8",
  "#f9a8d4",
  "#f472b6",
  "#ec4899",
  "#db2777",
  "#be185d",
  "#9d174d",
  "#831843",
  // Rose
  "#fff1f2",
  "#ffe4e6",
  "#fecdd3",
  "#fda4af",
  "#fb7185",
  "#f43f5e",
  "#e11d48",
  "#be123c",
  "#9f1239",
  "#881337",
];
