import { IFormTemplate } from "./interfaces";

export const FormTemplates: IFormTemplate[] = [
  {
    id: "form_template_001",
    category: "feedback",
    enabled: true,
    name: "Customer Feedback",
    description: "User feedback form for gathering insights.",
    form: {
      created_at: "",
      description: "Share your thoughts and help us improve! Please take a moment to provide your feedback.",
      email_notifications: false,
      email_notifications_to: null,
      id: "",
      name: "Customer Feedback",
      nebulaform_branding: true,
      new_submission_notification: false,
      owner_id: "",
      public_url: "",
      status: "draft",
      submit_text: "Submit Feedback",
      success_description: "Thank you for your feedback!",
      success_title: "Feedback Submitted",
      updated_at: "",
    },
    theme: {
      created_at: "",
      form_id: "",
      id: "",
      nebulaform_branding: true,
      numeric_blocks: false,
      primary_color: "slate",
      updated_at: "",
      uppercase_block_name: true,
      width: "centered",
    },
    blocks: [
      {
        created_at: "",
        description: "Enter your name to personalize your feedback.",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: 200,
        max_scale: null,
        min_char: 5,
        min_scale: null,
        name: "Full Name",
        options: null,
        placeholder: "Enter your name",
        position: 1,
        rating: null,
        required: true,
        show_char: true,
        type: "short_text",
        updated_at: "",
      },
      {
        created_at: "",
        description: "Share your thoughts and suggestions about your experience.",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: 500,
        max_scale: null,
        min_char: 10,
        min_scale: null,
        name: "Feedback",
        options: null,
        placeholder: "Tell us about your experience...",
        position: 2,
        rating: null,
        required: true,
        show_char: true,
        type: "paragraph_text",
        updated_at: "",
      },
      {
        created_at: "",
        description: "Rate your overall experience from 1 (poor) to 5 (excellent).",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: null,
        max_scale: 5,
        min_char: null,
        min_scale: 1,
        name: "Experience Rating",
        options: null,
        placeholder: null,
        position: 3,
        rating: 5,
        required: true,
        show_char: null,
        type: "star_rating",
        updated_at: "",
      },
    ],
    pro: false,
  },
  {
    id: "form_template_002",
    category: "survey",
    enabled: true,
    name: "Market Research Survey",
    description: "Survey form for gathering market research data.",
    form: {
      created_at: "",
      description:
        "Help us understand market trends and customer preferences by completing this short survey. Your insights are valuable",
      email_notifications: false,
      email_notifications_to: null,
      id: "",
      name: "Market Research Survey",
      nebulaform_branding: true,
      new_submission_notification: true,
      owner_id: "",
      public_url: "",
      status: "draft",
      submit_text: "Submit Survey",
      success_description: "Thank you for completing the survey!",
      success_title: "Survey Submitted",
      updated_at: "",
    },
    theme: {
      created_at: "",
      form_id: "",
      id: "",
      nebulaform_branding: true,
      numeric_blocks: true,
      primary_color: "teal",
      updated_at: "",
      uppercase_block_name: true,
      width: "full",
    },
    blocks: [
      {
        created_at: "",
        description: "Enter your company name to help us understand your business context.",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: 100,
        max_scale: null,
        min_char: 5,
        min_scale: null,
        name: "Company Name",
        options: null,
        placeholder: "Enter your company name",
        position: 1,
        rating: null,
        required: true,
        show_char: true,
        type: "short_text",
        updated_at: "",
      },
      {
        created_at: "",
        description: "Share your experience with our product, including any benefits or challenges you've encountered.",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: 300,
        max_scale: null,
        min_char: 10,
        min_scale: null,
        name: "Product Experience",
        options: null,
        placeholder: "Describe your experience with our product...",
        position: 2,
        rating: null,
        required: true,
        show_char: true,
        type: "paragraph_text",
        updated_at: "",
      },
      {
        created_at: "",
        description:
          "Rate your satisfaction with our product on a scale from 1 (Very Dissatisfied) to 10 (Very Satisfied).",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: null,
        max_scale: 10,
        min_char: null,
        min_scale: 1,
        name: "Satisfaction Rating",
        options: null,
        placeholder: null,
        position: 3,
        rating: 10,
        required: true,
        show_char: null,
        type: "custom_scale",
        updated_at: "",
      },
      {
        created_at: "",
        description: "Select the industry that best describes your business.",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: null,
        max_scale: null,
        min_char: null,
        min_scale: null,
        name: "Industry",
        options: ["Technology", "Healthcare", "Finance", "Retail", "Education", "Manufacturing", "Other"],
        placeholder: null,
        position: 4,
        rating: null,
        required: true,
        show_char: null,
        type: "dropdown_menu",
        updated_at: "",
      },
      {
        created_at: "",
        description: "Which features of our product do you use the most? (Select all that apply)",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: null,
        max_scale: null,
        min_char: null,
        min_scale: null,
        name: "Most Used Features",
        options: ["Dashboard Analytics", "Automated Reports", "User Management", "Custom Integrations", "API Access"],
        placeholder: null,
        position: 5,
        rating: null,
        required: true,
        show_char: null,
        type: "checkboxes",
        updated_at: "",
      },
      {
        created_at: "",
        description: "How likely are you to recommend our product to a colleague or friend?",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: null,
        max_scale: 5,
        min_char: null,
        min_scale: 1,
        name: "Recommendation Likelihood",
        options: null,
        placeholder: null,
        position: 6,
        rating: 5,
        required: true,
        show_char: null,
        type: "star_rating",
        updated_at: "",
      },
      {
        created_at: "",
        description: "What improvements would you like to see in our product?",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: 500,
        max_scale: null,
        min_char: 10,
        min_scale: null,
        name: "Product Improvements",
        options: null,
        placeholder: "Describe any features or improvements you’d like to see...",
        position: 7,
        rating: null,
        required: false,
        show_char: true,
        type: "paragraph_text",
        updated_at: "",
      },
      {
        created_at: "",
        description: "How many employees work in your company?",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: null,
        max_scale: null,
        min_char: 1,
        min_scale: null,
        name: "Company Size",
        options: null,
        placeholder: "Enter the number of employees",
        position: 8,
        rating: null,
        required: true,
        show_char: true,
        type: "number_input",
        updated_at: "",
      },
      {
        created_at: "",
        description: "Please provide your email address so we can follow up if needed.",
        form_id: "",
        id: "",
        is_identifier: true,
        max_char: null,
        max_scale: null,
        min_char: null,
        min_scale: null,
        name: "Email Address",
        options: null,
        placeholder: "Enter your email",
        position: 9,
        rating: null,
        required: true,
        show_char: null,
        type: "email_address",
        updated_at: "",
      },
    ],
    pro: true,
  },
  {
    id: "form_template_003",
    category: "registration",
    enabled: true,
    name: "Newsletter Signup",
    description: "Registration form for signing up for newsletters.",
    form: {
      created_at: "",
      description: "Stay updated with our latest news and exclusive content. Sign up for our newsletter today!",
      email_notifications: false,
      email_notifications_to: null,
      id: "",
      name: "Newsletter Signup",
      nebulaform_branding: true,
      new_submission_notification: true,
      owner_id: "",
      public_url: "",
      status: "draft",
      submit_text: "Sign Up",
      success_description: "Thanks for signing up! Please check your inbox.",
      success_title: "Sign Up Successful",
      updated_at: "",
    },
    theme: {
      created_at: "",
      form_id: "",
      id: "",
      nebulaform_branding: true,
      numeric_blocks: false,
      primary_color: "blue",
      updated_at: "",
      uppercase_block_name: true,
      width: "centered",
    },
    blocks: [
      {
        created_at: "",
        description: "Enter your full name to personalize your subscription.",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: 100,
        max_scale: null,
        min_char: 5,
        min_scale: null,
        name: "Full Name",
        options: null,
        placeholder: "Enter your full name",
        position: 1,
        rating: null,
        required: true,
        show_char: true,
        type: "short_text",
        updated_at: "",
      },
      {
        created_at: "",
        description: "Provide your email address to receive our latest updates and exclusive content.",
        form_id: "",
        id: "",
        is_identifier: true,
        max_char: 100,
        max_scale: null,
        min_char: 5,
        min_scale: null,
        name: "Email",
        options: null,
        placeholder: "Enter your email address",
        position: 2,
        rating: null,
        required: true,
        show_char: false,
        type: "email_address",
        updated_at: "",
      },
    ],
    pro: false,
  },
  {
    id: "form_template_004",
    category: "feedback",
    enabled: true,
    name: "Detailed Feedback",
    description: "Advanced feedback form with multiple questions for detailed insights.",
    form: {
      created_at: "",
      description:
        "Your detailed feedback helps us improve and better serve you. We appreciate your time and insights!",
      email_notifications: false,
      email_notifications_to: null,
      id: "",
      name: "Detailed Feedback",
      nebulaform_branding: true,
      new_submission_notification: true,
      owner_id: "",
      public_url: "",
      status: "draft",
      submit_text: "Submit Feedback",
      success_description: "Thanks for your detailed feedback!",
      success_title: "Feedback Submitted",
      updated_at: "",
    },
    theme: {
      created_at: "",
      form_id: "",
      id: "",
      nebulaform_branding: true,
      numeric_blocks: true,
      primary_color: "purple",
      updated_at: "",
      uppercase_block_name: true,
      width: "full",
    },
    blocks: [
      {
        created_at: "",
        description: "Please enter your full name so we can personalize your feedback.",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: 200,
        max_scale: null,
        min_char: 5,
        min_scale: null,
        name: "Full Name",
        options: null,
        placeholder: "Enter your name",
        position: 1,
        rating: null,
        required: true,
        show_char: true,
        type: "short_text",
        updated_at: "",
      },
      {
        created_at: "",
        description:
          "Describe your experience with our product in detail, including what you liked and what could be improved.",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: 500,
        max_scale: null,
        min_char: 10,
        min_scale: null,
        name: "Detailed Feedback",
        options: null,
        placeholder: "Tell us about your experience...",
        position: 2,
        rating: null,
        required: true,
        show_char: true,
        type: "paragraph_text",
        updated_at: "",
      },
      {
        created_at: "",
        description: "Rate your overall experience with our product from 1 (Poor) to 5 (Excellent).",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: null,
        max_scale: 5,
        min_char: null,
        min_scale: 1,
        name: "Overall Rating",
        options: null,
        placeholder: null,
        position: 3,
        rating: 5,
        required: true,
        show_char: null,
        type: "star_rating",
        updated_at: "",
      },
      {
        created_at: "",
        description: "Which aspects of our product do you find most valuable? (Select all that apply)",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: null,
        max_scale: null,
        min_char: null,
        min_scale: null,
        name: "Most Valuable Aspects",
        options: ["Ease of use", "Customer support", "Feature set", "Performance & speed", "Pricing"],
        placeholder: null,
        position: 4,
        rating: null,
        required: true,
        show_char: null,
        type: "checkboxes",
        updated_at: "",
      },
      {
        created_at: "",
        description: "What areas do you think need improvement?",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: 500,
        max_scale: null,
        min_char: 10,
        min_scale: null,
        name: "Areas for Improvement",
        options: null,
        placeholder: "Describe what could be improved...",
        position: 5,
        rating: null,
        required: true,
        show_char: true,
        type: "paragraph_text",
        updated_at: "",
      },
      {
        created_at: "",
        description: "How likely are you to continue using our product?",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: null,
        max_scale: 10,
        min_char: null,
        min_scale: 1,
        name: "Likelihood to Continue",
        options: null,
        placeholder: null,
        position: 6,
        rating: 10,
        required: true,
        show_char: null,
        type: "custom_scale",
        updated_at: "",
      },
      {
        created_at: "",
        description: "Would you recommend our product to others?",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: null,
        max_scale: null,
        min_char: null,
        min_scale: null,
        name: "Recommend to Others",
        options: ["Yes", "No", "Not Sure"],
        placeholder: null,
        position: 7,
        rating: null,
        required: true,
        show_char: null,
        type: "multiple_choice",
        updated_at: "",
      },
      {
        created_at: "",
        description: "How satisfied are you with our customer support?",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: null,
        max_scale: 5,
        min_char: null,
        min_scale: 1,
        name: "Customer Support Satisfaction",
        options: null,
        placeholder: null,
        position: 8,
        rating: 5,
        required: true,
        show_char: null,
        type: "star_rating",
        updated_at: "",
      },
      {
        created_at: "",
        description: "Please provide your email address in case we need to follow up with you.",
        form_id: "",
        id: "",
        is_identifier: true,
        max_char: null,
        max_scale: null,
        min_char: null,
        min_scale: null,
        name: "Email Address",
        options: null,
        placeholder: "Enter your email",
        position: 9,
        rating: null,
        required: true,
        show_char: null,
        type: "email_address",
        updated_at: "",
      },
    ],
    pro: true,
  },
  {
    id: "form_template_005",
    category: "survey",
    enabled: true,
    name: "Survey on Services",
    description: "Survey form with multiple choice questions for broad data collection.",
    form: {
      created_at: "",
      description: "Help us improve our services by sharing your thoughts. Your feedback is invaluable to us!",
      email_notifications: false,
      email_notifications_to: null,
      id: "",
      name: "Survey on Services",
      nebulaform_branding: true,
      new_submission_notification: true,
      owner_id: "",
      public_url: "",
      status: "draft",
      submit_text: "Submit Survey",
      success_description: "Your responses have been submitted!",
      success_title: "Survey Submitted",
      updated_at: "",
    },
    theme: {
      created_at: "",
      form_id: "",
      id: "",
      nebulaform_branding: true,
      numeric_blocks: true,
      primary_color: "orange",
      updated_at: "",
      uppercase_block_name: true,
      width: "full",
    },
    blocks: [
      {
        created_at: "",
        description: "Please provide your name so we can personalize your feedback.",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: 100,
        max_scale: null,
        min_char: 5,
        min_scale: null,
        name: "Full Name",
        options: null,
        placeholder: "Enter your name",
        position: 1,
        rating: null,
        required: true,
        show_char: true,
        type: "short_text",
        updated_at: "",
      },
      {
        created_at: "",
        description: "How would you rate our services? Select the option that best represents your experience.",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: null,
        max_scale: null,
        min_char: null,
        min_scale: null,
        name: "Service Satisfaction",
        options: ["Excellent", "Good", "Average", "Poor"],
        placeholder: null,
        position: 2,
        rating: null,
        required: true,
        show_char: null,
        type: "multiple_choice",
        updated_at: "",
      },
      {
        created_at: "",
        description: "Which of our services have you used? (Select all that apply)",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: null,
        max_scale: null,
        min_char: null,
        min_scale: null,
        name: "Services Used",
        options: ["Customer Support", "Product Consultation", "Technical Assistance", "Training", "Other"],
        placeholder: null,
        position: 3,
        rating: null,
        required: true,
        show_char: null,
        type: "checkboxes",
        updated_at: "",
      },
      {
        created_at: "",
        description: "What improvements would you like to see in our services?",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: 300,
        max_scale: null,
        min_char: 10,
        min_scale: null,
        name: "Service Improvements",
        options: null,
        placeholder: "Describe any improvements...",
        position: 4,
        rating: null,
        required: false,
        show_char: true,
        type: "paragraph_text",
        updated_at: "",
      },
      {
        created_at: "",
        description: "How often do you use our services?",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: null,
        max_scale: null,
        min_char: null,
        min_scale: null,
        name: "Usage Frequency",
        options: ["Daily", "Weekly", "Monthly", "Rarely", "First Time"],
        placeholder: null,
        position: 5,
        rating: null,
        required: true,
        show_char: null,
        type: "multiple_choice",
        updated_at: "",
      },
      {
        created_at: "",
        description: "How likely are you to recommend our services to others?",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: null,
        max_scale: 10,
        min_char: null,
        min_scale: 1,
        name: "Recommendation Likelihood",
        options: null,
        placeholder: null,
        position: 6,
        rating: 10,
        required: true,
        show_char: null,
        type: "custom_scale",
        updated_at: "",
      },
      {
        created_at: "",
        description: "Would you like to be contacted for follow-up questions?",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: null,
        max_scale: null,
        min_char: null,
        min_scale: null,
        name: "Follow-Up Contact",
        options: ["Yes", "No"],
        placeholder: null,
        position: 7,
        rating: null,
        required: true,
        show_char: null,
        type: "multiple_choice",
        updated_at: "",
      },
      {
        created_at: "",
        description: "Please provide your email if you would like to receive follow-up communication.",
        form_id: "",
        id: "",
        is_identifier: true,
        max_char: 100,
        max_scale: null,
        min_char: 5,
        min_scale: null,
        name: "Email Address",
        options: null,
        placeholder: "Enter your email",
        position: 8,
        rating: null,
        required: true,
        show_char: true,
        type: "email_address",
        updated_at: "",
      },
    ],
    pro: true,
  },
  {
    id: "form_template_006",
    category: "review",
    enabled: true,
    name: "Product Review",
    description: "Collect reviews from customers about products they purchased.",
    form: {
      created_at: "",
      description: "Share your thoughts on our product! Your feedback helps us improve and provide better experiences.",
      email_notifications: false,
      email_notifications_to: null,
      id: "",
      name: "Product Review",
      nebulaform_branding: true,
      new_submission_notification: true,
      owner_id: "",
      public_url: "",
      status: "draft",
      submit_text: "Submit Review",
      success_description: "Thank you for your feedback! Your review has been submitted.",
      success_title: "Review Submitted",
      updated_at: "",
    },
    theme: {
      created_at: "",
      form_id: "",
      id: "",
      nebulaform_branding: true,
      numeric_blocks: true,
      primary_color: "purple",
      updated_at: "",
      uppercase_block_name: true,
      width: "full",
    },
    blocks: [
      {
        created_at: "",
        description: "Please rate your overall satisfaction with the product.",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: null,
        max_scale: 5,
        min_char: null,
        min_scale: 1,
        name: "Product Satisfaction",
        options: null,
        placeholder: null,
        position: 1,
        rating: 5,
        required: true,
        show_char: null,
        type: "star_rating",
        updated_at: "",
      },
      {
        created_at: "",
        description: "What did you like the most about the product?",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: 250,
        max_scale: null,
        min_char: 10,
        min_scale: null,
        name: "What You Liked",
        options: null,
        placeholder: "Describe what you liked",
        position: 2,
        rating: null,
        required: true,
        show_char: true,
        type: "paragraph_text",
        updated_at: "",
      },
      {
        created_at: "",
        description: "What improvements would you suggest for the product?",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: 250,
        max_scale: null,
        min_char: 10,
        min_scale: null,
        name: "Improvements",
        options: null,
        placeholder: "Provide any suggestions",
        position: 3,
        rating: null,
        required: false,
        show_char: true,
        type: "paragraph_text",
        updated_at: "",
      },
      {
        created_at: "",
        description: "Would you recommend this product to others?",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: null,
        max_scale: null,
        min_char: null,
        min_scale: null,
        name: "Product Recommendation",
        options: ["Yes", "No"],
        placeholder: null,
        position: 4,
        rating: null,
        required: true,
        show_char: null,
        type: "multiple_choice",
        updated_at: "",
      },
    ],
    pro: true,
  },
  {
    id: "form_template_007",
    category: "registration",
    enabled: true,
    name: "Event Registration",
    description: "Collect registrations for your upcoming events.",
    form: {
      created_at: "",
      description: "Register for our upcoming event. We look forward to seeing you!",
      email_notifications: false,
      email_notifications_to: null,
      id: "",
      name: "Event Registration",
      nebulaform_branding: true,
      new_submission_notification: true,
      owner_id: "",
      public_url: "",
      status: "draft",
      submit_text: "Register Now",
      success_description: "Thank you for registering! We’ll send you further details soon.",
      success_title: "Registration Successful",
      updated_at: "",
    },
    theme: {
      created_at: "",
      form_id: "",
      id: "",
      nebulaform_branding: true,
      numeric_blocks: true,
      primary_color: "red",
      updated_at: "",
      uppercase_block_name: true,
      width: "full",
    },
    blocks: [
      {
        created_at: "",
        description: "Please provide your name for the event registration.",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: 100,
        max_scale: null,
        min_char: 5,
        min_scale: null,
        name: "Full Name",
        options: null,
        placeholder: "Enter your full name",
        position: 1,
        rating: null,
        required: true,
        show_char: true,
        type: "short_text",
        updated_at: "",
      },
      {
        created_at: "",
        description: "What event are you registering for?",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: 100,
        max_scale: null,
        min_char: 5,
        min_scale: null,
        name: "Event Name",
        options: null,
        placeholder: "Enter event name",
        position: 2,
        rating: null,
        required: true,
        show_char: true,
        type: "short_text",
        updated_at: "",
      },
      {
        created_at: "",
        description: "Please provide your email address for event updates.",
        form_id: "",
        id: "",
        is_identifier: true,
        max_char: 100,
        max_scale: null,
        min_char: 5,
        min_scale: null,
        name: "Email Address",
        options: null,
        placeholder: "Enter your email address",
        position: 3,
        rating: null,
        required: true,
        show_char: true,
        type: "email_address",
        updated_at: "",
      },
      {
        created_at: "",
        description: "Would you like to receive updates about future events?",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: null,
        max_scale: null,
        min_char: null,
        min_scale: null,
        name: "Event Updates",
        options: ["Yes", "No"],
        placeholder: null,
        position: 4,
        rating: null,
        required: false,
        show_char: null,
        type: "multiple_choice",
        updated_at: "",
      },
    ],
    pro: false,
  },
  {
    id: "form_template_008",
    category: "feedback",
    enabled: true,
    name: "Employee Feedback",
    description: "Collect feedback from employees about workplace satisfaction and suggestions.",
    form: {
      created_at: "",
      description: "We value your input! Please share your thoughts on the workplace and how we can improve.",
      email_notifications: false,
      email_notifications_to: null,
      id: "",
      name: "Employee Feedback",
      nebulaform_branding: true,
      new_submission_notification: true,
      owner_id: "",
      public_url: "",
      status: "draft",
      submit_text: "Submit Feedback",
      success_description: "Thank you for your feedback! We appreciate your input.",
      success_title: "Feedback Submitted",
      updated_at: "",
    },
    theme: {
      created_at: "",
      form_id: "",
      id: "",
      nebulaform_branding: true,
      numeric_blocks: true,
      primary_color: "slate",
      updated_at: "",
      uppercase_block_name: true,
      width: "full",
    },
    blocks: [
      {
        created_at: "",
        description: "How satisfied are you with the current work environment?",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: null,
        max_scale: 5,
        min_char: null,
        min_scale: 1,
        name: "Work Environment Satisfaction",
        options: null,
        placeholder: null,
        position: 1,
        rating: 5,
        required: true,
        show_char: null,
        type: "star_rating",
        updated_at: "",
      },
      {
        created_at: "",
        description: "What can be improved in the workplace?",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: 250,
        max_scale: null,
        min_char: 10,
        min_scale: null,
        name: "Improvements",
        options: null,
        placeholder: "Provide suggestions for improvements",
        position: 2,
        rating: null,
        required: true,
        show_char: true,
        type: "paragraph_text",
        updated_at: "",
      },
      {
        created_at: "",
        description: "Do you feel supported by your team leader?",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: null,
        max_scale: null,
        min_char: null,
        min_scale: null,
        name: "Team Leader Support",
        options: ["Yes", "No"],
        placeholder: null,
        position: 3,
        rating: null,
        required: true,
        show_char: null,
        type: "multiple_choice",
        updated_at: "",
      },
      {
        created_at: "",
        description: "Would you recommend this company to others as a great place to work?",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: null,
        max_scale: null,
        min_char: null,
        min_scale: null,
        name: "Company Recommendation",
        options: ["Yes", "No"],
        placeholder: null,
        position: 4,
        rating: null,
        required: true,
        show_char: null,
        type: "multiple_choice",
        updated_at: "",
      },
    ],
    pro: true,
  },
  {
    id: "form_template_009",
    category: "survey",
    enabled: true,
    name: "Customer Satisfaction Survey",
    description: "Understand how satisfied your customers are with your products or services.",
    form: {
      created_at: "",
      description: "We value your feedback! Please let us know how satisfied you are with our services.",
      email_notifications: false,
      email_notifications_to: null,
      id: "",
      name: "Customer Satisfaction Survey",
      nebulaform_branding: true,
      new_submission_notification: true,
      owner_id: "",
      public_url: "",
      status: "draft",
      submit_text: "Submit Feedback",
      success_description: "Thank you for your feedback! We appreciate your input.",
      success_title: "Feedback Submitted",
      updated_at: "",
    },
    theme: {
      created_at: "",
      form_id: "",
      id: "",
      nebulaform_branding: true,
      numeric_blocks: true,
      primary_color: "green",
      updated_at: "",
      uppercase_block_name: true,
      width: "full",
    },
    blocks: [
      {
        created_at: "",
        description: "How satisfied are you with our product?",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: null,
        max_scale: 5,
        min_char: null,
        min_scale: 1,
        name: "Product Satisfaction",
        options: null,
        placeholder: null,
        position: 1,
        rating: 5,
        required: true,
        show_char: null,
        type: "star_rating",
        updated_at: "",
      },
      {
        created_at: "",
        description: "What do you like the most about our product?",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: 250,
        max_scale: null,
        min_char: 10,
        min_scale: null,
        name: "Likes",
        options: null,
        placeholder: "Describe what you liked",
        position: 2,
        rating: null,
        required: true,
        show_char: true,
        type: "paragraph_text",
        updated_at: "",
      },
      {
        created_at: "",
        description: "What improvements would you suggest?",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: 250,
        max_scale: null,
        min_char: 10,
        min_scale: null,
        name: "Improvements",
        options: null,
        placeholder: "Provide suggestions for improvements",
        position: 3,
        rating: null,
        required: false,
        show_char: true,
        type: "paragraph_text",
        updated_at: "",
      },
      {
        created_at: "",
        description: "Would you recommend our product to others?",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: null,
        max_scale: null,
        min_char: null,
        min_scale: null,
        name: "Recommendation",
        options: ["Yes", "No"],
        placeholder: null,
        position: 4,
        rating: null,
        required: true,
        show_char: null,
        type: "multiple_choice",
        updated_at: "",
      },
      {
        created_at: "",
        description: "Please provide your email address to receive updates.",
        form_id: "",
        id: "",
        is_identifier: true,
        max_char: 100,
        max_scale: null,
        min_char: 5,
        min_scale: null,
        name: "Email Address",
        options: null,
        placeholder: "Enter your email address",
        position: 5,
        rating: null,
        required: true,
        show_char: true,
        type: "email_address",
        updated_at: "",
      },
    ],
    pro: true,
  },
  {
    id: "form_template_010",
    category: "feedback",
    enabled: true,
    name: "Product Feedback",
    description: "Gather feedback from customers about the products they’ve purchased.",
    form: {
      created_at: "",
      description: "We’d love to hear your thoughts on the product you purchased.",
      email_notifications: false,
      email_notifications_to: null,
      id: "",
      name: "Product Feedback",
      nebulaform_branding: true,
      new_submission_notification: true,
      owner_id: "",
      public_url: "",
      status: "draft",
      submit_text: "Submit Feedback",
      success_description: "Thank you for sharing your feedback!",
      success_title: "Feedback Submitted",
      updated_at: "",
    },
    theme: {
      created_at: "",
      form_id: "",
      id: "",
      nebulaform_branding: true,
      numeric_blocks: true,
      primary_color: "blue",
      updated_at: "",
      uppercase_block_name: true,
      width: "full",
    },
    blocks: [
      {
        created_at: "",
        description: "How would you rate the product quality?",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: null,
        max_scale: 5,
        min_char: null,
        min_scale: 1,
        name: "Product Quality Rating",
        options: null,
        placeholder: null,
        position: 1,
        rating: 5,
        required: true,
        show_char: null,
        type: "star_rating",
        updated_at: "",
      },
      {
        created_at: "",
        description: "What did you like about the product?",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: 250,
        max_scale: null,
        min_char: 10,
        min_scale: null,
        name: "Likes",
        options: null,
        placeholder: "Describe what you liked",
        position: 2,
        rating: null,
        required: true,
        show_char: true,
        type: "paragraph_text",
        updated_at: "",
      },
      {
        created_at: "",
        description: "What can be improved about the product?",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: 250,
        max_scale: null,
        min_char: 10,
        min_scale: null,
        name: "Improvements",
        options: null,
        placeholder: "Provide any suggestions",
        position: 3,
        rating: null,
        required: false,
        show_char: true,
        type: "paragraph_text",
        updated_at: "",
      },
      {
        created_at: "",
        description: "Would you buy this product again?",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: null,
        max_scale: null,
        min_char: null,
        min_scale: null,
        name: "Repeat Purchase",
        options: ["Yes", "No"],
        placeholder: null,
        position: 4,
        rating: null,
        required: true,
        show_char: null,
        type: "multiple_choice",
        updated_at: "",
      },
      {
        created_at: "",
        description: "Please provide your email address for further updates.",
        form_id: "",
        id: "",
        is_identifier: true,
        max_char: 100,
        max_scale: null,
        min_char: 5,
        min_scale: null,
        name: "Email Address",
        options: null,
        placeholder: "Enter your email address",
        position: 5,
        rating: null,
        required: true,
        show_char: true,
        type: "email_address",
        updated_at: "",
      },
    ],
    pro: true,
  },
];
