import { IFormTemplate } from "./interfaces";

export const FormTemplates: IFormTemplate[] = [
  // Feedback form (Basic)
  {
    id: "form_template_001",
    category: "feedback",
    enabled: true,
    form: {
      created_at: "",
      description: "User feedback form for gathering insights.",
      email_notifications: false,
      email_notifications_to: null,
      id: "",
      name: "Customer Feedback",
      nebulaform_branding: true,
      new_submission_notification: false,
      owner_id: "",
      public_url: "",
      status: "draft",
      submit_text: "Submit Feedback",
      success_description: "Thank you for your feedback!",
      success_title: "Feedback Submitted",
      updated_at: "",
    },
    theme: {
      created_at: "",
      form_id: "",
      id: "",
      nebulaform_branding: true,
      numeric_blocks: false,
      primary_color: "slate",
      updated_at: "",
      uppercase_block_name: true,
      width: "centered",
    },
    blocks: [
      {
        created_at: "",
        description: "Enter your name to personalize your feedback.",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: 200,
        max_scale: null,
        min_char: 5,
        min_scale: null,
        name: "Full Name",
        options: null,
        placeholder: "Enter your name",
        position: 1,
        rating: null,
        required: true,
        show_char: true,
        type: "short_text",
        updated_at: "",
      },
      {
        created_at: "",
        description: "Share your thoughts and suggestions about your experience.",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: 500,
        max_scale: null,
        min_char: 10,
        min_scale: null,
        name: "Feedback",
        options: null,
        placeholder: "Tell us about your experience...",
        position: 2,
        rating: null,
        required: true,
        show_char: true,
        type: "paragraph_text",
        updated_at: "",
      },
      {
        created_at: "",
        description: "Rate your overall experience from 1 (poor) to 5 (excellent).",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: null,
        max_scale: 5,
        min_char: null,
        min_scale: 1,
        name: "Experience Rating",
        options: null,
        placeholder: null,
        position: 3,
        rating: 5,
        required: true,
        show_char: null,
        type: "star_rating",
        updated_at: "",
      },
    ],
    pro: false,
  },

  // Survey form (PRO)
  {
    id: "form_template_002",
    category: "survey",
    enabled: true,
    form: {
      created_at: "",
      description: "Survey form for gathering market research data.",
      email_notifications: false,
      email_notifications_to: null,
      id: "",
      name: "Market Research Survey",
      nebulaform_branding: true,
      new_submission_notification: true,
      owner_id: "",
      public_url: "",
      status: "draft",
      submit_text: "Submit Survey",
      success_description: "Thank you for completing the survey!",
      success_title: "Survey Submitted",
      updated_at: "",
    },
    theme: {
      created_at: "",
      form_id: "",
      id: "",
      nebulaform_branding: true,
      numeric_blocks: true,
      primary_color: "teal",
      updated_at: "",
      uppercase_block_name: true,
      width: "full",
    },
    blocks: [
      {
        created_at: "",
        description: "Enter your company name to help us understand your business context.",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: 100,
        max_scale: null,
        min_char: 5,
        min_scale: null,
        name: "Company Name",
        options: null,
        placeholder: "Enter your company name",
        position: 1,
        rating: null,
        required: true,
        show_char: true,
        type: "short_text",
        updated_at: "",
      },
      {
        created_at: "",
        description: "Share your experience with our product, including any benefits or challenges you've encountered.",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: 300,
        max_scale: null,
        min_char: 10,
        min_scale: null,
        name: "Product Experience",
        options: null,
        placeholder: "Describe your experience with our product...",
        position: 2,
        rating: null,
        required: true,
        show_char: true,
        type: "paragraph_text",
        updated_at: "",
      },
      {
        created_at: "",
        description:
          "Rate your satisfaction with our product on a scale from 1 (Very Dissatisfied) to 10 (Very Satisfied).",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: null,
        max_scale: 10,
        min_char: null,
        min_scale: 1,
        name: "Satisfaction Rating",
        options: null,
        placeholder: null,
        position: 3,
        rating: 10,
        required: true,
        show_char: null,
        type: "custom_scale",
        updated_at: "",
      },
    ],
    pro: true,
  },

  // Registration form (Basic)
  {
    id: "form_template_003",
    category: "registration",
    enabled: true,
    form: {
      created_at: "",
      description: "Registration form for signing up for newsletters.",
      email_notifications: true,
      email_notifications_to: null,
      id: "",
      name: "Newsletter Signup",
      nebulaform_branding: true,
      new_submission_notification: true,
      owner_id: "",
      public_url: "",
      status: "draft",
      submit_text: "Sign Up",
      success_description: "Thanks for signing up! Please check your inbox.",
      success_title: "Sign Up Successful",
      updated_at: "",
    },
    theme: {
      created_at: "",
      form_id: "",
      id: "",
      nebulaform_branding: true,
      numeric_blocks: false,
      primary_color: "blue",
      updated_at: "",
      uppercase_block_name: true,
      width: "centered",
    },
    blocks: [
      {
        created_at: "",
        description: "Enter your full name to personalize your subscription.",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: 100,
        max_scale: null,
        min_char: 5,
        min_scale: null,
        name: "Full Name",
        options: null,
        placeholder: "Enter your full name",
        position: 1,
        rating: null,
        required: true,
        show_char: true,
        type: "short_text",
        updated_at: "",
      },
      {
        created_at: "",
        description: "Provide your email address to receive our latest updates and exclusive content.",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: 100,
        max_scale: null,
        min_char: 5,
        min_scale: null,
        name: "Email",
        options: null,
        placeholder: "Enter your email address",
        position: 2,
        rating: null,
        required: true,
        show_char: false,
        type: "email_address",
        updated_at: "",
      },
    ],
    pro: false,
  },

  // Advanced Feedback form (PRO)
  {
    id: "form_template_004",
    category: "feedback",
    enabled: true,
    form: {
      created_at: "",
      description: "Advanced feedback form with multiple questions for detailed insights.",
      email_notifications: true,
      email_notifications_to: null,
      id: "",
      name: "Detailed Feedback",
      nebulaform_branding: true,
      new_submission_notification: true,
      owner_id: "",
      public_url: "",
      status: "draft",
      submit_text: "Submit Feedback",
      success_description: "Thanks for your detailed feedback!",
      success_title: "Feedback Submitted",
      updated_at: "",
    },
    theme: {
      created_at: "",
      form_id: "",
      id: "",
      nebulaform_branding: true,
      numeric_blocks: true,
      primary_color: "purple",
      updated_at: "",
      uppercase_block_name: true,
      width: "full",
    },
    blocks: [
      {
        created_at: "",
        description: "Please enter your full name so we can personalize your feedback.",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: 200,
        max_scale: null,
        min_char: 5,
        min_scale: null,
        name: "Full Name",
        options: null,
        placeholder: "Enter your name",
        position: 1,
        rating: null,
        required: true,
        show_char: true,
        type: "short_text",
        updated_at: "",
      },
      {
        created_at: "",
        description:
          "Describe your experience with our product in detail, including what you liked and what could be improved.",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: 500,
        max_scale: null,
        min_char: 10,
        min_scale: null,
        name: "Detailed Feedback",
        options: null,
        placeholder: "Tell us about your experience...",
        position: 2,
        rating: null,
        required: true,
        show_char: true,
        type: "paragraph_text",
        updated_at: "",
      },
      {
        created_at: "",
        description: "Rate your overall experience with our product from 1 (Poor) to 5 (Excellent).",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: null,
        max_scale: 5,
        min_char: null,
        min_scale: 1,
        name: "Overall Rating",
        options: null,
        placeholder: null,
        position: 3,
        rating: 5,
        required: true,
        show_char: null,
        type: "star_rating",
        updated_at: "",
      },
    ],
    pro: true,
  },

  // Survey form with Multiple Choice (PRO)
  {
    id: "form_template_005",
    category: "survey",
    enabled: true,
    form: {
      created_at: "",
      description: "Survey form with multiple choice questions for broad data collection.",
      email_notifications: false,
      email_notifications_to: null,
      id: "",
      name: "Survey on Services",
      nebulaform_branding: true,
      new_submission_notification: true,
      owner_id: "",
      public_url: "",
      status: "draft",
      submit_text: "Submit Survey",
      success_description: "Your responses have been submitted!",
      success_title: "Survey Submitted",
      updated_at: "",
    },
    theme: {
      created_at: "",
      form_id: "",
      id: "",
      nebulaform_branding: true,
      numeric_blocks: true,
      primary_color: "orange",
      updated_at: "",
      uppercase_block_name: true,
      width: "full",
    },
    blocks: [
      {
        created_at: "",
        description: "Please provide your name so we can personalize your feedback.",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: 100,
        max_scale: null,
        min_char: 5,
        min_scale: null,
        name: "Full Name",
        options: null,
        placeholder: "Enter your name",
        position: 1,
        rating: null,
        required: true,
        show_char: true,
        type: "short_text",
        updated_at: "",
      },
      {
        created_at: "",
        description: "How would you rate our services? Select the option that best represents your experience.",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: null,
        max_scale: null,
        min_char: null,
        min_scale: null,
        name: "Service Satisfaction",
        options: ["Excellent", "Good", "Average", "Poor"],
        placeholder: null,
        position: 2,
        rating: null,
        required: true,
        show_char: null,
        type: "multiple_choice",
        updated_at: "",
      },
    ],
    pro: true,
  },
];
