import {
  basicForms,
  basicPricing,
  basicSubmissions,
  freeTrialForms,
  freeTrialPeriod,
  freeTrialPricing,
  freeTrialSubmissions,
  proForms,
  proPricing,
  proSubmissions,
} from "./envs";
import { IPlan2 } from "./interfaces";

export const plans: IPlan2[] = [
  {
    name: "Free Trial",
    price: freeTrialPricing,
    type: "free_trial",
    isMostPopular: false,
    freeTrialDuration: freeTrialPeriod,
    features: [
      { description: `Up to ${freeTrialForms} forms`, comingSoon: false },
      { description: `Up to ${freeTrialSubmissions} submissions`, comingSoon: false },
      { description: "Basic support (24h response time)", comingSoon: false },
      { description: "Basic templates", comingSoon: false },
      { description: "Integrations", comingSoon: true },
      { description: "Email notifications", comingSoon: true },
    ],
    ctaButton: "Start Free Trial",
  },
  {
    name: "Basic",
    price: basicPricing,
    type: "basic",
    isMostPopular: false,
    freeTrialDuration: null,
    features: [
      { description: `Up to ${basicForms} forms`, comingSoon: false },
      { description: `Up to ${basicSubmissions} submissions`, comingSoon: false },
      { description: "Basic support (24h response time)", comingSoon: false },
      { description: "Basic analytics (Submissions tracking)", comingSoon: false },
      { description: "Basic templates", comingSoon: false },
      { description: "Integrations)", comingSoon: true },
      { description: "Email notifications", comingSoon: true },
    ],
    ctaButton: "Choose Basic Plan",
  },
  {
    name: "Pro",
    price: proPricing,
    type: "pro",
    isMostPopular: true,
    freeTrialDuration: null,
    features: [
      { description: `Up to ${proForms} forms`, comingSoon: false },
      { description: `Up to ${proSubmissions} submissions`, comingSoon: false },
      { description: "Priority support (6h response time)", comingSoon: false },
      { description: "Remove branding", comingSoon: false },
      { description: "Data export (CSV)", comingSoon: false },
      { description: "Premium templates", comingSoon: false },
      { description: "Premium analytics", comingSoon: true },
      { description: "Email notifications", comingSoon: true },
      { description: "Premium integrations", comingSoon: true },
      { description: "More to come", comingSoon: false },
    ],
    ctaButton: "Choose Pro Plan",
  },
];
