import { createTranslator } from "use-intl/core";
import { IFormTemplate } from "./interfaces";

export const FormTemplates: IFormTemplate[] = [
  {
    id: "form_template_001",
    category: "feedback",
    enabled: true,
    name: "Product Feedback",
    description: "Gather feedback from customers about the products they’ve purchased.",
    form: {
      created_at: "",
      description: "We’d love to hear your thoughts on the product you purchased.",
      email_notifications: false,
      email_notifications_to: null,
      id: "",
      name: "Product Feedback",
      nebulaform_branding: true,
      new_submission_notification: true,
      owner_id: "",
      public_url: "",
      status: "draft",
      submit_text: "Submit Feedback",
      success_description: "Thank you for sharing your feedback!",
      success_title: "Feedback Submitted",
      updated_at: "",
    },
    theme: {
      created_at: "",
      form_id: "",
      id: "",
      nebulaform_branding: true,
      numeric_blocks: true,
      primary_color: "slate",
      updated_at: "",
      uppercase_block_name: true,
      width: "full",
    },
    blocks: [
      {
        created_at: "",
        description: "How would you rate the product quality?",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: null,
        max_scale: 5,
        min_char: null,
        min_scale: 1,
        name: "Product Quality Rating",
        options: null,
        placeholder: null,
        position: 1,
        rating: 5,
        required: true,
        show_char: null,
        type: "star_rating",
        updated_at: "",
      },
      {
        created_at: "",
        description: "What did you like about the product?",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: 250,
        max_scale: null,
        min_char: 10,
        min_scale: null,
        name: "Likes",
        options: null,
        placeholder: "Describe what you liked",
        position: 2,
        rating: null,
        required: true,
        show_char: true,
        type: "paragraph_text",
        updated_at: "",
      },
      {
        created_at: "",
        description: "What can be improved about the product?",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: 250,
        max_scale: null,
        min_char: 10,
        min_scale: null,
        name: "Improvements",
        options: null,
        placeholder: "Provide any suggestions",
        position: 3,
        rating: null,
        required: false,
        show_char: true,
        type: "paragraph_text",
        updated_at: "",
      },
      {
        created_at: "",
        description: "Would you buy this product again?",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: null,
        max_scale: null,
        min_char: null,
        min_scale: null,
        name: "Repeat Purchase",
        options: ["Yes", "No"],
        placeholder: null,
        position: 4,
        rating: null,
        required: true,
        show_char: null,
        type: "multiple_choice",
        updated_at: "",
      },
      {
        created_at: "",
        description: "Please provide your email address for further updates.",
        form_id: "",
        id: "",
        is_identifier: true,
        max_char: 100,
        max_scale: null,
        min_char: 5,
        min_scale: null,
        name: "Email Address",
        options: null,
        placeholder: "Enter your email address",
        position: 5,
        rating: null,
        required: true,
        show_char: true,
        type: "email_address",
        updated_at: "",
      },
    ],
    pro: false,
  },
  {
    id: "form_template_002",
    category: "survey",
    enabled: true,
    name: "Market Research Survey",
    description: "Survey form for gathering market research data.",
    form: {
      created_at: "",
      description:
        "Help us understand market trends and customer preferences by completing this short survey. Your insights are valuable",
      email_notifications: false,
      email_notifications_to: null,
      id: "",
      name: "Market Research Survey",
      nebulaform_branding: true,
      new_submission_notification: true,
      owner_id: "",
      public_url: "",
      status: "draft",
      submit_text: "Submit Survey",
      success_description: "Thank you for completing the survey!",
      success_title: "Survey Submitted",
      updated_at: "",
    },
    theme: {
      created_at: "",
      form_id: "",
      id: "",
      nebulaform_branding: true,
      numeric_blocks: true,
      primary_color: "slate",
      updated_at: "",
      uppercase_block_name: true,
      width: "full",
    },
    blocks: [
      {
        created_at: "",
        description: "Enter your company name to help us understand your business context.",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: 100,
        max_scale: null,
        min_char: 5,
        min_scale: null,
        name: "Company Name",
        options: null,
        placeholder: "Enter your company name",
        position: 1,
        rating: null,
        required: true,
        show_char: true,
        type: "short_text",
        updated_at: "",
      },
      {
        created_at: "",
        description: "Share your experience with our product, including any benefits or challenges you've encountered.",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: 300,
        max_scale: null,
        min_char: 10,
        min_scale: null,
        name: "Product Experience",
        options: null,
        placeholder: "Describe your experience with our product...",
        position: 2,
        rating: null,
        required: true,
        show_char: true,
        type: "paragraph_text",
        updated_at: "",
      },
      {
        created_at: "",
        description:
          "Rate your satisfaction with our product on a scale from 1 (Very Dissatisfied) to 10 (Very Satisfied).",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: null,
        max_scale: 10,
        min_char: null,
        min_scale: 1,
        name: "Satisfaction Rating",
        options: null,
        placeholder: null,
        position: 3,
        rating: 10,
        required: true,
        show_char: null,
        type: "custom_scale",
        updated_at: "",
      },
      {
        created_at: "",
        description: "Select the industry that best describes your business.",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: null,
        max_scale: null,
        min_char: null,
        min_scale: null,
        name: "Industry",
        options: ["Technology", "Healthcare", "Finance", "Retail", "Education", "Manufacturing", "Other"],
        placeholder: null,
        position: 4,
        rating: null,
        required: true,
        show_char: null,
        type: "dropdown_menu",
        updated_at: "",
      },
      {
        created_at: "",
        description: "Which features of our product do you use the most? (Select all that apply)",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: null,
        max_scale: null,
        min_char: null,
        min_scale: null,
        name: "Most Used Features",
        options: ["Dashboard Analytics", "Automated Reports", "User Management", "Custom Integrations", "API Access"],
        placeholder: null,
        position: 5,
        rating: null,
        required: true,
        show_char: null,
        type: "checkboxes",
        updated_at: "",
      },
      {
        created_at: "",
        description: "How likely are you to recommend our product to a colleague or friend?",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: null,
        max_scale: 5,
        min_char: null,
        min_scale: 1,
        name: "Recommendation Likelihood",
        options: null,
        placeholder: null,
        position: 6,
        rating: 5,
        required: true,
        show_char: null,
        type: "star_rating",
        updated_at: "",
      },
      {
        created_at: "",
        description: "What improvements would you like to see in our product?",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: 500,
        max_scale: null,
        min_char: 10,
        min_scale: null,
        name: "Product Improvements",
        options: null,
        placeholder: "Describe any features or improvements you’d like to see...",
        position: 7,
        rating: null,
        required: false,
        show_char: true,
        type: "paragraph_text",
        updated_at: "",
      },
      {
        created_at: "",
        description: "How many employees work in your company?",
        form_id: "",
        id: "",
        is_identifier: false,
        max_char: null,
        max_scale: null,
        min_char: 1,
        min_scale: null,
        name: "Company Size",
        options: null,
        placeholder: "Enter the number of employees",
        position: 8,
        rating: null,
        required: true,
        show_char: true,
        type: "number_input",
        updated_at: "",
      },
      {
        created_at: "",
        description: "Please provide your email address so we can follow up if needed.",
        form_id: "",
        id: "",
        is_identifier: true,
        max_char: null,
        max_scale: null,
        min_char: null,
        min_scale: null,
        name: "Email Address",
        options: null,
        placeholder: "Enter your email",
        position: 9,
        rating: null,
        required: true,
        show_char: null,
        type: "email_address",
        updated_at: "",
      },
    ],
    pro: true,
  },
];

export const getTemplates = async (locale: string): Promise<IFormTemplate[]> => {
  const messages = (await import(`@/locales/${locale}.json`)).default;
  const t = createTranslator({ locale, messages });
  return [
    {
      id: "form_template_001",
      category: "feedback",
      enabled: true,
      name: t("templates.t1_name"),
      description: t("templates.t1_desc"),
      form: {
        created_at: "",
        description: t("templates.t1_f_desc"),
        email_notifications: false,
        email_notifications_to: null,
        id: "",
        name: t("templates.t1_f_name"),
        nebulaform_branding: true,
        new_submission_notification: true,
        owner_id: "",
        public_url: "",
        status: "draft",
        submit_text: t("templates.t1_submit"),
        success_description: t("templates.t1_suc_desc"),
        success_title: t("templates.t1_suc_title"),
        updated_at: "",
      },
      theme: {
        created_at: "",
        form_id: "",
        id: "",
        nebulaform_branding: true,
        numeric_blocks: true,
        primary_color: "slate",
        updated_at: "",
        uppercase_block_name: true,
        width: "full",
      },
      blocks: [
        {
          created_at: "",
          description: t("templates.t1_b2_desc"),
          form_id: "",
          id: "",
          is_identifier: false,
          max_char: null,
          max_scale: 5,
          min_char: null,
          min_scale: 1,
          name: t("templates.t1_b1_name"),
          options: null,
          placeholder: null,
          position: 1,
          rating: 5,
          required: true,
          show_char: null,
          type: "star_rating",
          updated_at: "",
        },
        {
          created_at: "",
          description: t("templates.t1_b3_desc"),
          form_id: "",
          id: "",
          is_identifier: false,
          max_char: 250,
          max_scale: null,
          min_char: 10,
          min_scale: null,
          name: t("templates.t1_b3_name"),
          options: null,
          placeholder: t("templates.t1_b3_desc"),
          position: 2,
          rating: null,
          required: true,
          show_char: true,
          type: "paragraph_text",
          updated_at: "",
        },
        {
          created_at: "",
          description: t("templates.t1_b4_desc"),
          form_id: "",
          id: "",
          is_identifier: false,
          max_char: 250,
          max_scale: null,
          min_char: 10,
          min_scale: null,
          name: t("templates.t1_b4_name"),
          options: null,
          placeholder: t("templates.t1_b4_desc"),
          position: 3,
          rating: null,
          required: false,
          show_char: true,
          type: "paragraph_text",
          updated_at: "",
        },
        {
          created_at: "",
          description: t("templates.t1_b5_desc"),
          form_id: "",
          id: "",
          is_identifier: false,
          max_char: null,
          max_scale: null,
          min_char: null,
          min_scale: null,
          name: t("templates.t1_b5_name"),
          options: ["Yes", "No"],
          placeholder: null,
          position: 4,
          rating: null,
          required: true,
          show_char: null,
          type: "multiple_choice",
          updated_at: "",
        },
        {
          created_at: "",
          description: t("templates.t1_b6_desc"),
          form_id: "",
          id: "",
          is_identifier: true,
          max_char: 100,
          max_scale: null,
          min_char: 5,
          min_scale: null,
          name: t("templates.t1_b6_name"),
          options: null,
          placeholder: t("templates.t1_b6_desc"),
          position: 5,
          rating: null,
          required: true,
          show_char: true,
          type: "email_address",
          updated_at: "",
        },
      ],
      pro: false,
    },
    {
      id: "form_template_002",
      category: "survey",
      enabled: true,
      name: t("templates.t2_name"),
      description: t("templates.t2_desc"),
      form: {
        created_at: "",
        description: t("templates.t2_f_desc"),
        email_notifications: false,
        email_notifications_to: null,
        id: "",
        name: t("templates.t2_f_name"),
        nebulaform_branding: true,
        new_submission_notification: true,
        owner_id: "",
        public_url: "",
        status: "draft",
        submit_text: t("templates.t2_submit"),
        success_description: t("templates.t2_suc_desc"),
        success_title: t("templates.t2_suc_title"),
        updated_at: "",
      },
      theme: {
        created_at: "",
        form_id: "",
        id: "",
        nebulaform_branding: true,
        numeric_blocks: true,
        primary_color: "slate",
        updated_at: "",
        uppercase_block_name: true,
        width: "full",
      },
      blocks: [
        {
          created_at: "",
          description: t("templates.t2_b1_desc"),
          form_id: "",
          id: "",
          is_identifier: false,
          max_char: 100,
          max_scale: null,
          min_char: 5,
          min_scale: null,
          name: t("templates.t2_b1_name"),
          options: null,
          placeholder: t("templates.t2_b1_desc"),
          position: 1,
          rating: null,
          required: true,
          show_char: true,
          type: "short_text",
          updated_at: "",
        },
        {
          created_at: "",
          description: t("templates.t2_b2_desc"),
          form_id: "",
          id: "",
          is_identifier: false,
          max_char: 300,
          max_scale: null,
          min_char: 10,
          min_scale: null,
          name: t("templates.t2_b2_name"),
          options: null,
          placeholder: t("templates.t2_b2_desc"),
          position: 2,
          rating: null,
          required: true,
          show_char: true,
          type: "paragraph_text",
          updated_at: "",
        },
        {
          created_at: "",
          description: t("templates.t2_b3_desc"),
          form_id: "",
          id: "",
          is_identifier: false,
          max_char: null,
          max_scale: 10,
          min_char: null,
          min_scale: 1,
          name: t("templates.t2_b3_name"),
          options: null,
          placeholder: null,
          position: 3,
          rating: 10,
          required: true,
          show_char: null,
          type: "custom_scale",
          updated_at: "",
        },
        {
          created_at: "",
          description: t("templates.t2_b4_desc"),
          form_id: "",
          id: "",
          is_identifier: false,
          max_char: null,
          max_scale: null,
          min_char: null,
          min_scale: null,
          name: t("templates.t2_b4_name"),
          options: [
            t("templates.t2_b4_op1"),
            t("templates.t2_b4_op2"),
            t("templates.t2_b4_op3"),
            t("templates.t2_b4_op4"),
            t("templates.t2_b4_op5"),
            t("templates.t2_b4_op6"),
            t("templates.t2_b4_op7"),
          ],
          placeholder: null,
          position: 4,
          rating: null,
          required: true,
          show_char: null,
          type: "dropdown_menu",
          updated_at: "",
        },
        {
          created_at: "",
          description: t("templates.t2_b5_desc"),
          form_id: "",
          id: "",
          is_identifier: false,
          max_char: null,
          max_scale: null,
          min_char: null,
          min_scale: null,
          name: t("templates.t2_b5_name"),
          options: [
            t("templates.t2_b5_op1"),
            t("templates.t2_b5_op2"),
            t("templates.t2_b5_op3"),
            t("templates.t2_b5_op4"),
            t("templates.t2_b5_op5"),
          ],
          placeholder: null,
          position: 5,
          rating: null,
          required: true,
          show_char: null,
          type: "checkboxes",
          updated_at: "",
        },
        {
          created_at: "",
          description: t("templates.t2_b6_desc"),
          form_id: "",
          id: "",
          is_identifier: false,
          max_char: null,
          max_scale: 5,
          min_char: null,
          min_scale: 1,
          name: t("templates.t2_b6_name"),
          options: null,
          placeholder: null,
          position: 6,
          rating: 5,
          required: true,
          show_char: null,
          type: "star_rating",
          updated_at: "",
        },
        {
          created_at: "",
          description: t("templates.t2_b7_desc"),
          form_id: "",
          id: "",
          is_identifier: false,
          max_char: 500,
          max_scale: null,
          min_char: 10,
          min_scale: null,
          name: t("templates.t2_b7_name"),
          options: null,
          placeholder: t("templates.t2_b7_desc"),
          position: 7,
          rating: null,
          required: false,
          show_char: true,
          type: "paragraph_text",
          updated_at: "",
        },
        {
          created_at: "",
          description: t("templates.t2_b8_desc"),
          form_id: "",
          id: "",
          is_identifier: false,
          max_char: null,
          max_scale: null,
          min_char: 1,
          min_scale: null,
          name: t("templates.t2_b8_name"),
          options: null,
          placeholder: t("templates.t2_b8_desc"),
          position: 8,
          rating: null,
          required: true,
          show_char: true,
          type: "number_input",
          updated_at: "",
        },
        {
          created_at: "",
          description: t("templates.t2_b9_desc"),
          form_id: "",
          id: "",
          is_identifier: true,
          max_char: 100,
          max_scale: null,
          min_char: 5,
          min_scale: null,
          name: t("templates.t2_b9_name"),
          options: null,
          placeholder: t("templates.t2_b9_desc"),
          position: 9,
          rating: null,
          required: true,
          show_char: true,
          type: "email_address",
          updated_at: "",
        },
      ],
      pro: true,
    },
  ];
};
